feature (refs dplan-11493): add new event Interface
demos-europe/demosplan-addon pull request #107
Opened 2024-04-30 08:35 UTC by jalalifardemos

**Ticket** :  https://demoseurope.youtrack.cloud/issue/DPLAN-11493/Uber-E-Mail-Import-eingereichte-STN-konnen-nicht-geloscht-werden

Description: Add new Interface for DeleteEmailImportedStatementEvent

2024-05-02 05:10 UTC, bakridemos requested changes

2024-05-02 05:41 UTC, jalalifardemos commented on src/Contracts/Events/DeleteEmailImportedStatementEventInterface.php
> +
done in [79e93e4](https://github.com/demos-europe/demosplan-addon/pull/107/commits/79e93e4053465f20d712c61b284104de72d8c167)

2024-05-02 06:50 UTC, mussbach requested changes

2024-05-02 06:50 UTC, mussbach commented on src/Contracts/Events/DeleteEmailImportedStatementEventInterface.php
> +interface DeleteEmailImportedStatementEventInterface
I would introduce a generic `StatementPreDeleteEvent` that can be used for multiple purposes

2024-05-02 11:52 UTC, jalalifardemos commented on src/Contracts/Events/DeleteEmailImportedStatementEventInterface.php
> +interface DeleteEmailImportedStatementEventInterface
done in [7d93eca](https://github.com/demos-europe/demosplan-addon/pull/107/commits/7d93eca1abbf759f982509cc31c93e2d42ddcf1b)

2024-05-02 12:37 UTC, mussbach requested changes
one minor remark

2024-05-02 12:37 UTC, mussbach commented on CHANGELOG.md
> +- add interface for new event DeleteEmailImportedStatementEvent
```suggestion
- add interface for new event StatementPreDeleteEventInterface
```

2024-05-02 12:40 UTC, jalalifardemos commented on CHANGELOG.md
> +- add interface for new event DeleteEmailImportedStatementEvent
done in [d70cb84](https://github.com/demos-europe/demosplan-addon/pull/107/commits/d70cb84f32c8d13bfce0d927bf7bff8640c77397)

2024-05-03 07:59 UTC, mussbach approved these changes
lgtm

2024-05-03 08:47 UTC, bakridemos approved these changes
lgtm

2024-05-21 12:06 UTC, merged