feature (refs ADO-17195): create ParagraphFactoryInterface.php
demos-europe/demosplan-addon pull request #116
Opened 2024-06-17 11:31 UTC by jalalifardemos

Ticket: https://www.dev.diplanung.de/DefaultCollection/BOP-HH/_workitems/edit/17195

Description: create a factory for paragraph entity

2024-06-28 11:38 UTC, breierDemos requested changes
Code Review only

It seams that both files have missing a new line after the closing bracket.
Changelog entry is missing.

2024-06-28 11:38 UTC, breierDemos commented on src/Contracts/Handler/ParagraphHandlerInterface.php
> +}
Empty line before closing bracket can be deleted.

2024-08-06 08:35 UTC, jalalifardemos commented on src/Contracts/Handler/ParagraphHandlerInterface.php
> +}
done in [d121525](https://github.com/demos-europe/demosplan-addon/pull/116/commits/d1215254b109407013cdbd0065755b6e05ed0146)

2024-08-06 08:36 UTC, MoritzMandler approved these changes
lgtm

2024-08-06 08:36 UTC, bakridemos approved these changes

2024-08-06 10:14 UTC, mussbach commented on CHANGELOG.md
> +## v0.39 (2024-08-06)
Please do not change version and content in one PR as you usually cannot know for sure that this PR is the next version.

2024-08-06 10:14 UTC, mussbach commented on composer.json
> +  "version": "v0.39"
Please do not change version and content in one PR as you usually cannot know for sure that this PR is the next version

2024-08-06 10:14 UTC, merged