Feat t30254 add contracts
demos-europe/demosplan-addon pull request #22
Opened 2023-01-23 07:51 UTC by bakridemos

**Ticket:** https://yaits.demos-deutschland.de/T30254

Description: add contracts 

- adjust resourcetypes interfaces

Delete the checkbox if it doesn't apply/isn't necessary.

- [ ] Link all relevant tickets

2023-02-01 12:12 UTC, AlexMenschoid approved these changes
lgtm, code review only

2023-02-06 11:26 UTC, graupnerdemos requested changes
Can you move JsonApiClient directly to the Addon that uses it? As this quite a quickshot of an api client approach, I'd rather not establish it as the de-facto solution in the base package.

2023-02-06 14:18 UTC, bakridemos commented
> Can you move JsonApiClient directly to the Addon that uses it? As this quite a quickshot of an api client approach, I'd rather not establish it as the de-facto solution in the base package.

done https://github.com/demos-europe/demosplan-addon/pull/22/commits/5abe90612dabcc7059fd1ecd62981e970395015f

2023-02-07 12:56 UTC, graupnerdemos approved these changes

2023-02-07 13:14 UTC, merged