F t31336 adjust and add contracts
demos-europe/demosplan-addon pull request #32
Opened 2023-02-22 08:05 UTC by bakridemos

Ticket: T31336

Description: add needed contracts

2023-03-03 08:53 UTC, mussbach requested changes

2023-03-03 08:53 UTC, mussbach commented on src/Contracts/Entities/ElementsInterface.php
> +    public const FILE_TYPE_ANSCHREIBEN = 'Anschreiben';
shouldn't this rather be in the specific addon?

2023-03-03 08:53 UTC, mussbach commented on src/Contracts/Exceptions/AddonContentMandatoryFieldsException.php
> +use Exception;
`use Throwable;` missing

2023-03-03 09:28 UTC, bakridemos commented on src/Contracts/Entities/ElementsInterface.php
> +    public const FILE_TYPE_ANSCHREIBEN = 'Anschreiben';
they are used in core too, they have to be hier to be availble for both, Xbauleitplanung addon and the core

2023-03-03 09:32 UTC, bakridemos commented on src/Contracts/Exceptions/AddonContentMandatoryFieldsException.php
> +use Exception;
thx, done in https://github.com/demos-europe/demosplan-addon/pull/32/commits/9893a5074d2666845964ab2a5e044b8321766a8e

2023-03-03 14:55 UTC, mussbach commented on src/Contracts/Entities/ElementsInterface.php
> +    public const FILE_TYPE_ANSCHREIBEN = 'Anschreiben';
But the ones below are not

2023-03-06 06:14 UTC, bakridemos commented on src/Contracts/Entities/ElementsInterface.php
> +    public const FILE_TYPE_ANSCHREIBEN = 'Anschreiben';
u are right, there are many constants that are not used ( not in core and not in addon), i thought it is better to keep them all together, so i moved them all in ElementsInterface.

2023-03-06 07:22 UTC, mussbach commented on src/Contracts/Entities/ElementsInterface.php
> +    public const FILE_TYPE_ANSCHREIBEN = 'Anschreiben';
The ones that are not used in core are all potentially used in XBauleiplanung addon. I would move all of them there.

2023-03-06 08:24 UTC, bakridemos commented on src/Contracts/Entities/ElementsInterface.php
> +    public const FILE_TYPE_ANSCHREIBEN = 'Anschreiben';
done in https://github.com/demos-europe/demosplan-addon/pull/32/commits/fdc250fd52d2001b2519140b8c401eeba3c2d3e1

2023-03-06 08:41 UTC, graupnerdemos approved these changes
99% lgtm, 1% accepted with marked hesitation.

2023-03-06 11:56 UTC, mussbach approved these changes

2023-03-06 13:47 UTC, merged