Define methods of CustomerInterface
demos-europe/demosplan-addon pull request #44
Opened 2023-04-05 09:56 UTC by martendemos

Define methods of CustomerInterface to add value to the usage of this interface

2023-04-05 10:20 UTC, bakridemos requested changes
i I don't see any use statements but Orga and Procedure are not availble in demosplan addon, if u want to define the interface methods here, u have to use OraInteface and ProcedureInterface, but may be u have to adjust too the parameters type of addOrga, getDefaultProcedureBlueprint and setDefaultProcedureBlueprint in core

2023-04-05 10:36 UTC, martendemos commented
Yes, I don't use any use statements, because there are not available at all.
Instead we maybe should replace the specific classes and use Interfaces for all of these. (except of Collection maybe)

Where do we want to define these interfaces and how make them available? I guess a new repository? :thinking:

2023-04-05 11:03 UTC, bakridemos commented
> Yes, I don't use any use statements, because there are not available at all. Instead we maybe should replace the specific classes and use Interfaces for all of these. (except of Collection maybe)
> 
> Where do we want to define these interfaces and how make them available? I guess a new repository? thinking

They are already in different repository ( here: https://github.com/demos-europe/demosplan-addon ). The interfaces are availble in core, demosplan addon is always required as dependency in core. And in the addons too ( make the core classes available in the addons was the purpose of these interfaces, they are used as contracts). The problem was if we define all interfaces methods, we will need more interfaces ( the core classes are not available in demosplan addon too, only interfaces implemented by those classes ), and we have to adjust these methods in core, and it's not so simple as said in some cases

2024-02-16 14:28 UTC, mussbach commented
@martendemos what happens with this PR?

2025-06-24 13:34 UTC, closed without merging