F t32212 add addon interfaces add necessary interfaces
demos-europe/demosplan-addon pull request #53
Opened 2023-05-19 10:07 UTC by jalalifardemos

Ticket:
https://yaits.demos-deutschland.de/T32212

Description:
add methods to interfaces / add new necessary interfaces...

the CoreEntityInterface now requires the method getEntityContentChangeIdentifier() which is not implemented by all entities inside addons. This has to be changed. - done in https://github.com/demos-europe/demosplan-addon-demospipes/pull/70

I did not finish the whole thing, but everything should be in a valid state at this point.

### Linked PRs (optional)
 - this PR is dependent on https://github.com/demos-europe/demosplan-core/pull/1254 and needs to be merged together.
 - this PR is dependent on https://github.com/demos-europe/demosplan-addon-demospipes/pull/70
###

- [ ] Tests updated/created
- [ ] Update documentation
- [x] Link all relevant tickets
- [ ] Move the tickets on the board accordingly

2023-06-07 18:57 UTC, MoritzMandler requested changes
Reviewed up to UserInterface - will be continued tomorrow

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/SingleDocumentVersionInterface.php
> +interface SingleDocumentVersionInterface extends UuidEntityInterface
The SingleDocumentVersion extends the CoreEntity - this interface should therefore implement the CoreEntityInterface

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementAttributeInterface.php
> +interface StatementAttributeInterface extends UuidEntityInterface
The StatementAttribute extends the CoreEntity and therefore this Interface should extend the CoreEntityInterface as well.

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementFieldDefinitionInterface.php
> +interface StatementFieldDefinitionInterface extends UuidEntityInterface
The StatementFieldDefinition extends the CoreEntity and therefore this Interface should extend the CoreEntityInterface as well.

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementFieldDefinitionInterface.php
> +    public function getId(): ?string;
getId() is not needed here - as present within the UuidEntityInterface

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementFormDefinitionInterface.php
> +interface StatementFormDefinitionInterface extends UuidEntityInterface
The StatementFormDefinition extends the CoreEntity - therefore this interface should extend the CoreEntityInterface as well.

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementFormDefinitionInterface.php
> +    public function getId(): ?string;
getId() is not needed here - as it gets added via UuidEntityInterface

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementFragmentInterface.php
> +interface StatementFragmentInterface extends UuidEntityInterface
The StatementFragment extends the CoreEntity - therefore this interface should extend the CoreEntityInterface as well.

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementFragmentInterface.php
> +    public function getId(): ?string;
getId() is not needed here - as it gets added via UuidEntityInterface

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementFragmentInterface.php
> +
StatementFragment::setVote($vote) is missing here

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementFragmentVersionInterface.php
> +interface StatementFragmentVersionInterface extends UuidEntityInterface
the CoreEntityInterface is missing here

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementInterface.php
> +interface StatementInterface extends UuidEntityInterface
the CoreEntityInterface is missing here

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementInterface.php
> +    public function getId(): ?string;
getId() is not needed here since UuidEntityInterface supports it

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementInterface.php
> +    public function getIdent(): ?string;
We do not want to implement the @deprecated methods here.

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementMetaInterface.php
> +interface StatementMetaInterface extends UuidEntityInterface
The CoreEntityInterface is missing here.

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/StatementMetaInterface.php
> +    public function getId(): ?string;
getId() is not needed here. (UuidEntityInterface)

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/SurveyInterface.php
> +interface SurveyInterface extends UuidEntityInterface
missing CoreEntityInterface

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/SurveyVoteInterface.php
> +interface SurveyVoteInterface extends UuidEntityInterface
missing CoreEntityInterface here.

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/TagInterface.php
> +interface TagInterface extends UuidEntityInterface
missing CoreEntityInterface here.

2023-06-07 18:57 UTC, MoritzMandler commented on src/Contracts/Entities/TagTopicInterface.php
> +interface TagTopicInterface extends UuidEntityInterface
missing CoreEntityInterface here.

2023-06-08 07:46 UTC, jalalifardemos commented on src/Contracts/Entities/BoilerplateCategoryInterface.php
> +
done

2023-06-08 12:40 UTC, jalalifardemos commented
All request Change done

2023-06-09 09:38 UTC, MoritzMandler requested changes

2023-06-09 09:38 UTC, MoritzMandler commented on src/Contracts/Entities/UserInterface.php
> +
since we do not implement the secureity/userinterface we could declare the `public function getSalt(): ?string`
method inside this interface

2023-06-09 09:55 UTC, jalalifardemos commented
Review Requesting Change is done

2023-06-09 10:12 UTC, MoritzMandler approved these changes
lgtm - big thanks!!!

2023-06-09 10:13 UTC, merged