feature (refs T29879): flesh out permission syntax
demos-europe/demosplan-addon pull request #6
Opened 2022-12-13 13:34 UTC by dresslerdemos

2022-12-14 13:16 UTC, AlexMenschoid requested changes
I think the structure is fine (except maybe my one concern) but I would like a bit more info in doc blocks to understand the relevance of some things like subgroups or what keys are even allowed in the condition array and when/how to use placeholders/references to parameters. I know this will be clearer if everything is used, but just a couple of sentences here and there might be helpful as this is going to be a very relevant basic element of addons.

2022-12-14 13:16 UTC, AlexMenschoid commented on src/Permission/Conditions/PropertyHasNotSize.php
> +                ],
As far as I can see, the inner array is either 'condition' or 'parameterCondition'. Could this not be another entry in the array itself to avoid nesting it deeper? Im pretty sure there is a good reason why not, but I don't really see it based on this PR and would like to avoid unnecessary nesting.

2022-12-14 13:36 UTC, dresslerdemos commented on src/Permission/Conditions/PropertyHasNotSize.php
> +                ],
The inner array is either `condition`, `parameterCondition` or `group`. This is an extension of the Drupal filter format, which already specifies `condition` and `group`.

2022-12-14 14:34 UTC, AlexMenschoid commented on src/Permission/Conditions/PropertyHasNotSize.php
> +                ],
See, I expected there to be a good reason. 👍🏼

2022-12-15 06:57 UTC, dresslerdemos commented
> what keys are even allowed in the condition array

The format is mostly specified with the `PermissionFilter` type-hint, though it does not cover some things like that there is no `value` field necessary when the `NULL`/`NOT NULL` operator is used or what type is allowed in the `value` field for the different operators or what operators are supported at all. I'm not yet sure how/where to document these details properly.

Regarding the general usage I've added a bit of documentation via 3d24a595cc445b5848ca7a9ec1e6eb54c3c9e48b.

2022-12-15 08:46 UTC, AlexMenschoid approved these changes
thx for adding a bit more documentation! I think this looks solid enough to go into actual usage and testing now. Please release it into the wild, wild world of Demosplan....

2022-12-16 10:33 UTC, merged