F add GetDatasheetFilePathAbsoluteEventInterface
demos-europe/demosplan-addon pull request #61
Opened 2023-06-28 05:14 UTC by bakridemos

Description: add a new event interface GetDatasheetFilePathAbsoluteEventInterface

2023-06-28 12:29 UTC, AlexMenschoid requested changes

2023-06-28 12:29 UTC, AlexMenschoid commented on src/Contracts/Events/GetDatasheetFilePathAbsoluteEventInterface.php
> +}
Please add the signatures for the public methods here. It will make using the event where needed easier.

2023-06-29 05:51 UTC, bakridemos commented on src/Contracts/Events/GetDatasheetFilePathAbsoluteEventInterface.php
> +}
done in https://github.com/demos-europe/demosplan-addon/pull/61/commits/55f7f02b2ef4ce18ae1af60081ad318531595436

2023-06-29 07:59 UTC, AlexMenschoid approved these changes
lgtm

2023-06-29 08:29 UTC, merged