F adjust user interface
demos-europe/demosplan-addon pull request #63
Opened 2023-07-04 19:10 UTC by bakridemos

Description:

2023-07-05 06:39 UTC, mussbach requested changes

2023-07-05 06:39 UTC, mussbach commented on src/Contracts/Entities/UserInterface.php
> +interface UserInterface extends SamlUserInterface, UuidEntityInterface, PasswordAuthenticatedUserInterface
Not so sure about this one. I see no reason why we should include this into the main UserInterface as it might depend on the implementation whether Saml is used or not. If you include it you need to the bundle to the composer.json

2023-07-05 10:44 UTC, bakridemos commented on src/Contracts/Entities/UserInterface.php
> +interface UserInterface extends SamlUserInterface, UuidEntityInterface, PasswordAuthenticatedUserInterface
i get your point thx, fixed in https://github.com/demos-europe/demosplan-addon/pull/63/commits/e7519951023c59a2e3c0d937d6e61e4ccc03aafa. The User entity is fixed too in the core pr.

2023-07-06 06:45 UTC, mussbach approved these changes
lgtm

2023-07-06 10:57 UTC, merged