F t29878 disconnect addon data storage
demos-europe/demosplan-addon pull request #87
Opened 2024-01-29 11:22 UTC by sierrazamudiodemos

**Ticket:** https://yaits.demos-deutschland.de/T29878

Description:
- We want to remove the dependency between DemosCore and addons
- DemosCoreEntities should not be used directly in demospipes neither maillane. Instead, interfaces provided by the middlelayer addons should be used.
- This PR is about linking the DemosCoreEntities to its corresponding Interfaces in the middlelayer Addon. 

How to review/test
- This PR is related to demospipes and maillane
- The 3 PRs should be merged to be able to test

Linked PRs (optional)

Delete the checkbox if it doesn't apply/isn't necessary.
- [ x] Move the tickets on the board accordingly

2024-01-31 10:46 UTC, breierDemos requested changes

2024-01-31 10:46 UTC, breierDemos commented on CHANGELOG.md
> +- Link references of DemosCoreEntities to Interfaces so that addons can use the interfaces
This line has to be under ## UNRELEASED not under ## v0.21 (2024-01-23)

2024-01-31 10:46 UTC, breierDemos commented on src/DependencyInjection/DemosPlanAddonExtension.php
> +class DemosPlanAddonExtension extends Extension implements PrependExtensionInterface
Maybe we must extend the AbstractAddonExtension?

2024-01-31 10:56 UTC, bakridemos requested changes

2024-01-31 10:56 UTC, bakridemos commented on src/DependencyInjection/DemosPlanAddonExtension.php
> +                    'DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface' => 'demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure',
we can not use hier something like 'demosplan\...', actually we want to remove them from the addons that's why i recommended to add these definitions in the doctrine yaml in core

2024-01-31 11:01 UTC, sierrazamudiodemos commented on src/DependencyInjection/DemosPlanAddonExtension.php
> +                    'DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface' => 'demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure',
hey @bakridemos this is the middle layer between each addon (demospipes, maillane etc) and demos core. As a middle layer, it knows about both projects, that is why I decided to do it here. I also checked it with Sami. What do you think? We could also review with sami this approach :)

2024-01-31 11:23 UTC, MoritzMandler commented on src/DependencyInjection/DemosPlanAddonExtension.php
> +                    'DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface' => 'demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure',
I thought the core and the addon both know about the middle layer - but the middle layer itself should not reference any
of them.

2024-01-31 14:34 UTC, sierrazamudiodemos reviewed
@breierDemos here 49c8b73529f5fb3a6423894edbf1818ef8560dce the commit for the UuidV4Generator. Addons demospipes, maillane and oracle-sgements will use this class instead of demoscore

2024-01-31 14:34 UTC, sierrazamudiodemos commented on src/DependencyInjection/DemosPlanAddonExtension.php
> +                    'DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface' => 'demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure',
1. the middlelayer has already some refereces to Core, for example in services file: https://github.com/demos-europe/demosplan-addon/blob/f_T29878_disconnect-addon-data-storage/config/services.yml

Yeah I see your point.

2024-01-31 15:14 UTC, breierDemos requested changes

2024-01-31 15:14 UTC, breierDemos commented on src/Contracts/Doctrine/UuidV4Generator.php
> +}
```suggestion
}

```

2024-01-31 15:20 UTC, breierDemos approved these changes

2024-02-01 18:59 UTC, bakridemos commented on src/DependencyInjection/DemosPlanAddonExtension.php
> +                    'DemosEurope\DemosplanAddon\Contracts\Entities\ProcedureInterface' => 'demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure',
good catch, actualy i think we don't need these two definitions here, and i think we can remove them from there. It's done in https://github.com/demos-europe/demosplan-addon/pull/88

2024-02-05 11:08 UTC, mussbach approved these changes
lgtm

2024-02-05 11:09 UTC, mussbach requested changes
the location needs to be adjusted. This is no contract

2024-02-05 15:17 UTC, mussbach approved these changes
lgtm, thx. Code review only

2024-02-06 11:07 UTC, breierDemos approved these changes

2024-02-06 14:09 UTC, merged